[2025-02-17T08:13:20.482+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ml_pipeline.extract manual__2025-02-17T08:13:17.225206+00:00 [queued]>
[2025-02-17T08:13:20.497+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ml_pipeline.extract manual__2025-02-17T08:13:17.225206+00:00 [queued]>
[2025-02-17T08:13:20.498+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-02-17T08:13:20.499+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-02-17T08:13:20.499+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-02-17T08:13:20.519+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): extract> on 2025-02-17 08:13:17.225206+00:00
[2025-02-17T08:13:20.529+0000] {standard_task_runner.py:52} INFO - Started process 2445 to run task
[2025-02-17T08:13:20.532+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'extract', 'manual__2025-02-17T08:13:17.225206+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/DAG-fraud.py', '--cfg-path', '/tmp/tmpoe7up5tp', '--error-file', '/tmp/tmpjgcqkj1a']
[2025-02-17T08:13:20.533+0000] {standard_task_runner.py:80} INFO - Job 32: Subtask extract
[2025-02-17T08:13:20.630+0000] {task_command.py:371} INFO - Running <TaskInstance: ml_pipeline.extract manual__2025-02-17T08:13:17.225206+00:00 [running]> on host 925d9315849a
[2025-02-17T08:13:20.730+0000] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=group1
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2025-02-17T08:13:17.225206+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-17T08:13:17.225206+00:00
[2025-02-17T08:13:20.746+0000] {base.py:68} INFO - Using connection ID 'postgres_***' for task execution.
[2025-02-17T08:13:20.762+0000] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.9/site-packages/pandas/io/sql.py:761 UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
[2025-02-17T08:13:21.505+0000] {DAG-fraud.py:41} INFO - Data extraction successful.
[2025-02-17T08:13:21.508+0000] {python.py:173} INFO - Done. Returned value was: None
[2025-02-17T08:13:21.527+0000] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=extract, execution_date=20250217T081317, start_date=20250217T081320, end_date=20250217T081321
[2025-02-17T08:13:21.590+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-17T08:13:21.670+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
