[2025-02-17T08:01:12.819+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ml_pipeline.extract manual__2025-02-17T08:01:08.620138+00:00 [queued]>
[2025-02-17T08:01:12.838+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ml_pipeline.extract manual__2025-02-17T08:01:08.620138+00:00 [queued]>
[2025-02-17T08:01:12.841+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-02-17T08:01:12.842+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-02-17T08:01:12.843+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-02-17T08:01:12.865+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): extract> on 2025-02-17 08:01:08.620138+00:00
[2025-02-17T08:01:12.884+0000] {standard_task_runner.py:52} INFO - Started process 2148 to run task
[2025-02-17T08:01:12.887+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'extract', 'manual__2025-02-17T08:01:08.620138+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/DAG-fraud.py', '--cfg-path', '/tmp/tmp6mzxz6rc', '--error-file', '/tmp/tmpdsk1opcl']
[2025-02-17T08:01:12.891+0000] {standard_task_runner.py:80} INFO - Job 20: Subtask extract
[2025-02-17T08:01:12.993+0000] {task_command.py:371} INFO - Running <TaskInstance: ml_pipeline.extract manual__2025-02-17T08:01:08.620138+00:00 [running]> on host 925d9315849a
[2025-02-17T08:01:13.105+0000] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=group1
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2025-02-17T08:01:08.620138+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-17T08:01:08.620138+00:00
[2025-02-17T08:01:13.140+0000] {base.py:68} INFO - Using connection ID 'postgres_***' for task execution.
[2025-02-17T08:01:13.183+0000] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.9/site-packages/pandas/io/sql.py:761 UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
[2025-02-17T08:01:13.975+0000] {DAG-fraud.py:41} INFO - Data extraction successful.
[2025-02-17T08:01:13.978+0000] {python.py:173} INFO - Done. Returned value was: None
[2025-02-17T08:01:13.997+0000] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=extract, execution_date=20250217T080108, start_date=20250217T080112, end_date=20250217T080113
[2025-02-17T08:01:14.031+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-17T08:01:14.092+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
