[2025-02-17T08:07:10.466+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ml_pipeline.extract manual__2025-02-17T08:07:06.604515+00:00 [queued]>
[2025-02-17T08:07:10.482+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ml_pipeline.extract manual__2025-02-17T08:07:06.604515+00:00 [queued]>
[2025-02-17T08:07:10.483+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-02-17T08:07:10.484+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-02-17T08:07:10.485+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-02-17T08:07:10.507+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): extract> on 2025-02-17 08:07:06.604515+00:00
[2025-02-17T08:07:10.520+0000] {standard_task_runner.py:52} INFO - Started process 2301 to run task
[2025-02-17T08:07:10.524+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'extract', 'manual__2025-02-17T08:07:06.604515+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/DAG-fraud.py', '--cfg-path', '/tmp/tmp_fib9d3g', '--error-file', '/tmp/tmplfdd6p0r']
[2025-02-17T08:07:10.528+0000] {standard_task_runner.py:80} INFO - Job 26: Subtask extract
[2025-02-17T08:07:10.613+0000] {task_command.py:371} INFO - Running <TaskInstance: ml_pipeline.extract manual__2025-02-17T08:07:06.604515+00:00 [running]> on host 925d9315849a
[2025-02-17T08:07:10.716+0000] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=group1
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2025-02-17T08:07:06.604515+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-17T08:07:06.604515+00:00
[2025-02-17T08:07:10.733+0000] {base.py:68} INFO - Using connection ID 'postgres_***' for task execution.
[2025-02-17T08:07:10.752+0000] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.9/site-packages/pandas/io/sql.py:761 UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
[2025-02-17T08:07:11.355+0000] {DAG-fraud.py:41} INFO - Data extraction successful.
[2025-02-17T08:07:11.358+0000] {python.py:173} INFO - Done. Returned value was: None
[2025-02-17T08:07:11.380+0000] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=extract, execution_date=20250217T080706, start_date=20250217T080710, end_date=20250217T080711
[2025-02-17T08:07:11.422+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-17T08:07:11.480+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
