[2025-02-17T07:51:48.187+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ml_pipeline.extract manual__2025-02-17T07:51:44.660586+00:00 [queued]>
[2025-02-17T07:51:48.205+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ml_pipeline.extract manual__2025-02-17T07:51:44.660586+00:00 [queued]>
[2025-02-17T07:51:48.205+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-02-17T07:51:48.206+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-02-17T07:51:48.207+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-02-17T07:51:48.228+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): extract> on 2025-02-17 07:51:44.660586+00:00
[2025-02-17T07:51:48.240+0000] {standard_task_runner.py:52} INFO - Started process 1950 to run task
[2025-02-17T07:51:48.243+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'extract', 'manual__2025-02-17T07:51:44.660586+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/DAG-fraud.py', '--cfg-path', '/tmp/tmpxvav0um7', '--error-file', '/tmp/tmpg3fynp5z']
[2025-02-17T07:51:48.245+0000] {standard_task_runner.py:80} INFO - Job 17: Subtask extract
[2025-02-17T07:51:48.338+0000] {task_command.py:371} INFO - Running <TaskInstance: ml_pipeline.extract manual__2025-02-17T07:51:44.660586+00:00 [running]> on host 925d9315849a
[2025-02-17T07:51:48.443+0000] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=group1
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2025-02-17T07:51:44.660586+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-17T07:51:44.660586+00:00
[2025-02-17T07:51:48.462+0000] {base.py:68} INFO - Using connection ID 'postgres_***' for task execution.
[2025-02-17T07:51:48.481+0000] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.9/site-packages/pandas/io/sql.py:761 UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
[2025-02-17T07:51:49.297+0000] {DAG-fraud.py:44} INFO - Data extraction successful.
[2025-02-17T07:51:49.303+0000] {python.py:173} INFO - Done. Returned value was: None
[2025-02-17T07:51:49.324+0000] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=extract, execution_date=20250217T075144, start_date=20250217T075148, end_date=20250217T075149
[2025-02-17T07:51:49.386+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-17T07:51:49.479+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
