[2025-02-17T16:07:26.228+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-17T16:07:26.249+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.send_email manual__2025-02-17T16:07:09.273706+00:00 [queued]>
[2025-02-17T16:07:26.262+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.send_email manual__2025-02-17T16:07:09.273706+00:00 [queued]>
[2025-02-17T16:07:26.263+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-17T16:07:26.280+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): send_email> on 2025-02-17 16:07:09.273706+00:00
[2025-02-17T16:07:26.287+0000] {standard_task_runner.py:72} INFO - Started process 235 to run task
[2025-02-17T16:07:26.289+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'send_email', 'manual__2025-02-17T16:07:09.273706+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/DAG-fraud.py', '--cfg-path', '/tmp/tmpz_0cdspk']
[2025-02-17T16:07:26.293+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask send_email
[2025-02-17T16:07:26.347+0000] {task_command.py:467} INFO - Running <TaskInstance: ml_pipeline.send_email manual__2025-02-17T16:07:09.273706+00:00 [running]> on host 8538735272b1
[2025-02-17T16:07:26.435+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='group1' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T16:07:09.273706+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-17T16:07:09.273706+00:00'
[2025-02-17T16:07:26.437+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-17T16:07:26.588+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/DAG-fraud.py", line 128, in send_email_notification
    email_task = SendGridOperator(
NameError: name 'SendGridOperator' is not defined
[2025-02-17T16:07:26.613+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=send_email, run_id=manual__2025-02-17T16:07:09.273706+00:00, execution_date=20250217T160709, start_date=20250217T160726, end_date=20250217T160726
[2025-02-17T16:07:26.648+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-17T16:07:26.649+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 23 for task send_email (name 'SendGridOperator' is not defined; 235)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/DAG-fraud.py", line 128, in send_email_notification
    email_task = SendGridOperator(
NameError: name 'SendGridOperator' is not defined
[2025-02-17T16:07:26.668+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-17T16:07:26.691+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-17T16:07:26.695+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
